### ISSUE TITLE
some  error

### ISSUE THREAD

**Issue by SoonyangZhang** [qdeconinck/minitopo-experiences#1]
I configure a virtual machine as the instruction. But When I run quic_mptcp_https_tests_expdes_wsp_lowbdp_quic.py, I got the following error.
raise Exception("File " + filename + " could not be put on remote server at path " + path)
Exception: File /home/zsy/minitopo-experiences/experiences/https_quic_20180801_202743_mptcp/0_d10.5qs0.048b51.83_1_d13.3qs0.063b45.38_nt_0_0_loss_0.00%_nt_1_0_loss_0.00%/0_d10.5qs0.048b51.83_1_d13.3qs0.063b45.38_nt_0_0_loss_0.00%_nt_1_0_loss_0.00% could not be put on remote server at path /mnt/tmpfs

**Comment by qdeconinck** [comment]
You don't have the directory `/mnt/tmpfs/` on your virtual machine. Either create it, or change the argument in the experiment to use another one.

**Comment by SoonyangZhang** [comment]
I did created the mentioned file. I changed tmpfs="/home/zsy/MyTest/results/", but get the same error. please give some help.

**Comment by qdeconinck** [comment]
Are you running the VM on localhost port 8022?

**Comment by SoonyangZhang** [comment]
How to get the VM runing on local host?  I put the minitopo-experiences files in my VM. And I am not quit understand the configuration REMOTE_SERVER_RUNNER_HOSTNAME = ["mininet@localhost"]
REMOTE_SERVER_RUNNER_PORT = ["8022"].

**Comment by qdeconinck** [comment]
The scripts inside this repository are not intended to be put on the VM itself. They should be on the machine you want to collect results.

The end of this blogpost might help for your setup.
https://multipath-quic.org/conext17/2017/12/09/artifacts-available.html

**Comment by SoonyangZhang** [comment]
need two VM?

**Comment by SoonyangZhang** [comment]
Really did not get how to get it running.
