### ISSUE TITLE
Import problem/Numpy problem-QUIC in mininet

### ISSUE THREAD

**Issue by new-p** [qdeconinck/minitopo-experiences#2]
Hi,

I am trying to reproduce the measurements related to QUIC in mininet VM, so I used the codes given in this repository.  I am using Ubuntu 20.04 and Python 2.7.6
After creating "generate_topo.py", "generate_xp.py" and "core.py", I created "quic_mptcp_https_tests_expdes_wsp_highbdp_loss_quic.py", but as I try to execute it using mininet environment (so using command:   sudo mn --custom quic_mptcp_https_tests_expdes_wsp_highbdp_loss_quic.py   ), I get the following error 

#Caught exception. Cleaning up...
#ImportError: No module named core

And when I try to execute it using python, I get the following error message:

#ImportError: No module named generate_topo

So, apparently there is a problem in the code at the importing part. Therefore, I cannot execute these codes and cannot recreate this experiment to get the measurements. 

Another problem that I encountered: I cannot import "numpy". Error message:
#No numpy module

I would really appreciate it if anyone could help me! Thank you very much!

**Comment by qdeconinck** [comment]
Are "generate_topo.py", "generate_xp.py" and "core.py" placed in a directory named "core"? Are your scripts placed in the same directory as the "core" folder? Also, the numpy issue is unrelated to this repository.

**Comment by ArthurCChen** [comment]
I came across the same problem and SOLVED it by changing
`from generate_topo import generateTopoFile, PATHS, DELAY, QUEUE_SIZE, QUEUING_DELAY, BANDWIDTH, LOSS, NETEM`
`from generate_xp import generateXpFile`
to
`from .generate_topo import generateTopoFile, PATHS, DELAY, QUEUE_SIZE, QUEUING_DELAY, BANDWIDTH, LOSS, NETEM`
`from .generate_xp import generateXpFile`
(add two dots)

Also, if you're using python3, `Queue` is not supported for python3. Change it to `from queue import Queue`
